### ISSUE TITLE
Add guidance on discord Token and permissions needed

### ISSUE THREAD

**Issue by alsmanifesto** [syncaide/discord-resource#5]
Hi, this resource has resulted very usefull to me, but I had a hard time trying to figure out what token is needed, how to create a bot, even to understand that i got to create one, and the bot configuration steps. I'm new to discord and I've had experience with webhook based integrations like the ones used by Slack. I found very convenient following this guide for all that process. Maybe parts of it or even the link to the guide can be included on the readme. 

https://github.com/reactiflux/discord-irc/wiki/Creating-a-discord-bot-&-getting-a-token

Thanks

**Comment by trivigy** [comment]
@alsmanifesto thanks. Added to readme.
